// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: message/request/set_public_access_info_request.proto

package request

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "pkg/message/common"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetPublicAccessInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client *common.ClientInfo `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	// Types that are assignable to Resouce:
	//
	//	*SetPublicAccessInfoRequest_HardwareResource
	//	*SetPublicAccessInfoRequest_InfoResource
	Resouce   isSetPublicAccessInfoRequest_Resouce `protobuf_oneof:"resouce"`
	Modiffier common.AccessModiffier               `protobuf:"varint,4,opt,name=modiffier,proto3,enum=common.AccessModiffier" json:"modiffier,omitempty"`
}

func (x *SetPublicAccessInfoRequest) Reset() {
	*x = SetPublicAccessInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_request_set_public_access_info_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPublicAccessInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPublicAccessInfoRequest) ProtoMessage() {}

func (x *SetPublicAccessInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_request_set_public_access_info_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPublicAccessInfoRequest.ProtoReflect.Descriptor instead.
func (*SetPublicAccessInfoRequest) Descriptor() ([]byte, []int) {
	return file_message_request_set_public_access_info_request_proto_rawDescGZIP(), []int{0}
}

func (x *SetPublicAccessInfoRequest) GetClient() *common.ClientInfo {
	if x != nil {
		return x.Client
	}
	return nil
}

func (m *SetPublicAccessInfoRequest) GetResouce() isSetPublicAccessInfoRequest_Resouce {
	if m != nil {
		return m.Resouce
	}
	return nil
}

func (x *SetPublicAccessInfoRequest) GetHardwareResource() common.HardwareResource {
	if x, ok := x.GetResouce().(*SetPublicAccessInfoRequest_HardwareResource); ok {
		return x.HardwareResource
	}
	return common.HardwareResource(0)
}

func (x *SetPublicAccessInfoRequest) GetInfoResource() common.InfoResource {
	if x, ok := x.GetResouce().(*SetPublicAccessInfoRequest_InfoResource); ok {
		return x.InfoResource
	}
	return common.InfoResource(0)
}

func (x *SetPublicAccessInfoRequest) GetModiffier() common.AccessModiffier {
	if x != nil {
		return x.Modiffier
	}
	return common.AccessModiffier(0)
}

type isSetPublicAccessInfoRequest_Resouce interface {
	isSetPublicAccessInfoRequest_Resouce()
}

type SetPublicAccessInfoRequest_HardwareResource struct {
	HardwareResource common.HardwareResource `protobuf:"varint,2,opt,name=hardware_resource,json=hardwareResource,proto3,enum=common.HardwareResource,oneof"`
}

type SetPublicAccessInfoRequest_InfoResource struct {
	InfoResource common.InfoResource `protobuf:"varint,3,opt,name=info_resource,json=infoResource,proto3,enum=common.InfoResource,oneof"`
}

func (*SetPublicAccessInfoRequest_HardwareResource) isSetPublicAccessInfoRequest_Resouce() {}

func (*SetPublicAccessInfoRequest_InfoResource) isSetPublicAccessInfoRequest_Resouce() {}

var File_message_request_set_public_access_info_request_proto protoreflect.FileDescriptor

var file_message_request_set_public_access_info_request_proto_rawDesc = []byte{
	0x0a, 0x34, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2f, 0x73, 0x65, 0x74, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x26, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x25, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x5f, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x02, 0x0a, 0x1a, 0x53, 0x65, 0x74, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12,
	0x47, 0x0a, 0x11, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x48, 0x00, 0x52, 0x10, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x69, 0x6e, 0x66, 0x6f,
	0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x66, 0x69,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x66, 0x69, 0x65,
	0x72, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x66, 0x69, 0x65, 0x72, 0x42, 0x09, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x63, 0x65, 0x42, 0x15, 0x5a, 0x13, 0x70, 0x6b, 0x67, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_request_set_public_access_info_request_proto_rawDescOnce sync.Once
	file_message_request_set_public_access_info_request_proto_rawDescData = file_message_request_set_public_access_info_request_proto_rawDesc
)

func file_message_request_set_public_access_info_request_proto_rawDescGZIP() []byte {
	file_message_request_set_public_access_info_request_proto_rawDescOnce.Do(func() {
		file_message_request_set_public_access_info_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_request_set_public_access_info_request_proto_rawDescData)
	})
	return file_message_request_set_public_access_info_request_proto_rawDescData
}

var file_message_request_set_public_access_info_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_request_set_public_access_info_request_proto_goTypes = []interface{}{
	(*SetPublicAccessInfoRequest)(nil), // 0: request.SetPublicAccessInfoRequest
	(*common.ClientInfo)(nil),          // 1: common.ClientInfo
	(common.HardwareResource)(0),       // 2: common.HardwareResource
	(common.InfoResource)(0),           // 3: common.InfoResource
	(common.AccessModiffier)(0),        // 4: common.AccessModiffier
}
var file_message_request_set_public_access_info_request_proto_depIdxs = []int32{
	1, // 0: request.SetPublicAccessInfoRequest.client:type_name -> common.ClientInfo
	2, // 1: request.SetPublicAccessInfoRequest.hardware_resource:type_name -> common.HardwareResource
	3, // 2: request.SetPublicAccessInfoRequest.info_resource:type_name -> common.InfoResource
	4, // 3: request.SetPublicAccessInfoRequest.modiffier:type_name -> common.AccessModiffier
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_message_request_set_public_access_info_request_proto_init() }
func file_message_request_set_public_access_info_request_proto_init() {
	if File_message_request_set_public_access_info_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_request_set_public_access_info_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPublicAccessInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_request_set_public_access_info_request_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SetPublicAccessInfoRequest_HardwareResource)(nil),
		(*SetPublicAccessInfoRequest_InfoResource)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_request_set_public_access_info_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_request_set_public_access_info_request_proto_goTypes,
		DependencyIndexes: file_message_request_set_public_access_info_request_proto_depIdxs,
		MessageInfos:      file_message_request_set_public_access_info_request_proto_msgTypes,
	}.Build()
	File_message_request_set_public_access_info_request_proto = out.File
	file_message_request_set_public_access_info_request_proto_rawDesc = nil
	file_message_request_set_public_access_info_request_proto_goTypes = nil
	file_message_request_set_public_access_info_request_proto_depIdxs = nil
}
