// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: message/response/get_using_hardware_resource_by_process_response.proto

package response

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "pkg/message/common"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUsingHardwareResourceByProcessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*GetUsingHardwareResourceByProcessResponse_Success_
	//	*GetUsingHardwareResourceByProcessResponse_Error
	Data isGetUsingHardwareResourceByProcessResponse_Data `protobuf_oneof:"data"`
}

func (x *GetUsingHardwareResourceByProcessResponse) Reset() {
	*x = GetUsingHardwareResourceByProcessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_response_get_using_hardware_resource_by_process_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsingHardwareResourceByProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsingHardwareResourceByProcessResponse) ProtoMessage() {}

func (x *GetUsingHardwareResourceByProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_response_get_using_hardware_resource_by_process_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsingHardwareResourceByProcessResponse.ProtoReflect.Descriptor instead.
func (*GetUsingHardwareResourceByProcessResponse) Descriptor() ([]byte, []int) {
	return file_message_response_get_using_hardware_resource_by_process_response_proto_rawDescGZIP(), []int{0}
}

func (m *GetUsingHardwareResourceByProcessResponse) GetData() isGetUsingHardwareResourceByProcessResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *GetUsingHardwareResourceByProcessResponse) GetSuccess() *GetUsingHardwareResourceByProcessResponse_Success {
	if x, ok := x.GetData().(*GetUsingHardwareResourceByProcessResponse_Success_); ok {
		return x.Success
	}
	return nil
}

func (x *GetUsingHardwareResourceByProcessResponse) GetError() *common.ErrorMessage {
	if x, ok := x.GetData().(*GetUsingHardwareResourceByProcessResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isGetUsingHardwareResourceByProcessResponse_Data interface {
	isGetUsingHardwareResourceByProcessResponse_Data()
}

type GetUsingHardwareResourceByProcessResponse_Success_ struct {
	Success *GetUsingHardwareResourceByProcessResponse_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type GetUsingHardwareResourceByProcessResponse_Error struct {
	Error *common.ErrorMessage `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetUsingHardwareResourceByProcessResponse_Success_) isGetUsingHardwareResourceByProcessResponse_Data() {
}

func (*GetUsingHardwareResourceByProcessResponse_Error) isGetUsingHardwareResourceByProcessResponse_Data() {
}

type GetUsingHardwareResourceByProcessResponse_SuccessElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource common.HardwareResource `protobuf:"varint,1,opt,name=resource,proto3,enum=common.HardwareResource" json:"resource,omitempty"`
	Data     []byte                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetUsingHardwareResourceByProcessResponse_SuccessElement) Reset() {
	*x = GetUsingHardwareResourceByProcessResponse_SuccessElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_response_get_using_hardware_resource_by_process_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsingHardwareResourceByProcessResponse_SuccessElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsingHardwareResourceByProcessResponse_SuccessElement) ProtoMessage() {}

func (x *GetUsingHardwareResourceByProcessResponse_SuccessElement) ProtoReflect() protoreflect.Message {
	mi := &file_message_response_get_using_hardware_resource_by_process_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsingHardwareResourceByProcessResponse_SuccessElement.ProtoReflect.Descriptor instead.
func (*GetUsingHardwareResourceByProcessResponse_SuccessElement) Descriptor() ([]byte, []int) {
	return file_message_response_get_using_hardware_resource_by_process_response_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetUsingHardwareResourceByProcessResponse_SuccessElement) GetResource() common.HardwareResource {
	if x != nil {
		return x.Resource
	}
	return common.HardwareResource(0)
}

func (x *GetUsingHardwareResourceByProcessResponse_SuccessElement) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetUsingHardwareResourceByProcessResponse_Success struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessName string                                                      `protobuf:"bytes,1,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	Datas       []*GetUsingHardwareResourceByProcessResponse_SuccessElement `protobuf:"bytes,2,rep,name=datas,proto3" json:"datas,omitempty"`
}

func (x *GetUsingHardwareResourceByProcessResponse_Success) Reset() {
	*x = GetUsingHardwareResourceByProcessResponse_Success{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_response_get_using_hardware_resource_by_process_response_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsingHardwareResourceByProcessResponse_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsingHardwareResourceByProcessResponse_Success) ProtoMessage() {}

func (x *GetUsingHardwareResourceByProcessResponse_Success) ProtoReflect() protoreflect.Message {
	mi := &file_message_response_get_using_hardware_resource_by_process_response_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsingHardwareResourceByProcessResponse_Success.ProtoReflect.Descriptor instead.
func (*GetUsingHardwareResourceByProcessResponse_Success) Descriptor() ([]byte, []int) {
	return file_message_response_get_using_hardware_resource_by_process_response_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetUsingHardwareResourceByProcessResponse_Success) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *GetUsingHardwareResourceByProcessResponse_Success) GetDatas() []*GetUsingHardwareResourceByProcessResponse_SuccessElement {
	if x != nil {
		return x.Datas
	}
	return nil
}

var File_message_response_get_using_hardware_resource_by_process_response_proto protoreflect.FileDescriptor

var file_message_response_get_using_hardware_resource_by_process_response_proto_rawDesc = []byte{
	0x0a, 0x46, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x73, 0x69, 0x6e, 0x67, 0x5f, 0x68, 0x61, 0x72,
	0x64, 0x77, 0x61, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x62,
	0x79, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x1a, 0x22, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x26, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x5f,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9f,
	0x03, 0x0a, 0x29, 0x47, 0x65, 0x74, 0x55, 0x73, 0x69, 0x6e, 0x67, 0x48, 0x61, 0x72, 0x64, 0x77,
	0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x42, 0x79, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3b, 0x2e,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x69, 0x6e,
	0x67, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x2c, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x1a, 0x5a, 0x0a, 0x0e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x34, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a,
	0x86, 0x01, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x58,
	0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x42, 0x2e,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x69, 0x6e,
	0x67, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x42, 0x16, 0x5a, 0x14, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_response_get_using_hardware_resource_by_process_response_proto_rawDescOnce sync.Once
	file_message_response_get_using_hardware_resource_by_process_response_proto_rawDescData = file_message_response_get_using_hardware_resource_by_process_response_proto_rawDesc
)

func file_message_response_get_using_hardware_resource_by_process_response_proto_rawDescGZIP() []byte {
	file_message_response_get_using_hardware_resource_by_process_response_proto_rawDescOnce.Do(func() {
		file_message_response_get_using_hardware_resource_by_process_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_response_get_using_hardware_resource_by_process_response_proto_rawDescData)
	})
	return file_message_response_get_using_hardware_resource_by_process_response_proto_rawDescData
}

var file_message_response_get_using_hardware_resource_by_process_response_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_message_response_get_using_hardware_resource_by_process_response_proto_goTypes = []interface{}{
	(*GetUsingHardwareResourceByProcessResponse)(nil),                // 0: response.GetUsingHardwareResourceByProcessResponse
	(*GetUsingHardwareResourceByProcessResponse_SuccessElement)(nil), // 1: response.GetUsingHardwareResourceByProcessResponse.SuccessElement
	(*GetUsingHardwareResourceByProcessResponse_Success)(nil),        // 2: response.GetUsingHardwareResourceByProcessResponse.Success
	(*common.ErrorMessage)(nil),                                      // 3: common.ErrorMessage
	(common.HardwareResource)(0),                                     // 4: common.HardwareResource
}
var file_message_response_get_using_hardware_resource_by_process_response_proto_depIdxs = []int32{
	2, // 0: response.GetUsingHardwareResourceByProcessResponse.success:type_name -> response.GetUsingHardwareResourceByProcessResponse.Success
	3, // 1: response.GetUsingHardwareResourceByProcessResponse.error:type_name -> common.ErrorMessage
	4, // 2: response.GetUsingHardwareResourceByProcessResponse.SuccessElement.resource:type_name -> common.HardwareResource
	1, // 3: response.GetUsingHardwareResourceByProcessResponse.Success.datas:type_name -> response.GetUsingHardwareResourceByProcessResponse.SuccessElement
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_message_response_get_using_hardware_resource_by_process_response_proto_init() }
func file_message_response_get_using_hardware_resource_by_process_response_proto_init() {
	if File_message_response_get_using_hardware_resource_by_process_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_response_get_using_hardware_resource_by_process_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsingHardwareResourceByProcessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_response_get_using_hardware_resource_by_process_response_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsingHardwareResourceByProcessResponse_SuccessElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_response_get_using_hardware_resource_by_process_response_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsingHardwareResourceByProcessResponse_Success); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_response_get_using_hardware_resource_by_process_response_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*GetUsingHardwareResourceByProcessResponse_Success_)(nil),
		(*GetUsingHardwareResourceByProcessResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_response_get_using_hardware_resource_by_process_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_response_get_using_hardware_resource_by_process_response_proto_goTypes,
		DependencyIndexes: file_message_response_get_using_hardware_resource_by_process_response_proto_depIdxs,
		MessageInfos:      file_message_response_get_using_hardware_resource_by_process_response_proto_msgTypes,
	}.Build()
	File_message_response_get_using_hardware_resource_by_process_response_proto = out.File
	file_message_response_get_using_hardware_resource_by_process_response_proto_rawDesc = nil
	file_message_response_get_using_hardware_resource_by_process_response_proto_goTypes = nil
	file_message_response_get_using_hardware_resource_by_process_response_proto_depIdxs = nil
}
