// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: message/response/get_info_resource_response.proto

package response

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "pkg/message/common"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInfoResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*GetInfoResourceResponse_Success_
	//	*GetInfoResourceResponse_Error
	Data isGetInfoResourceResponse_Data `protobuf_oneof:"data"`
}

func (x *GetInfoResourceResponse) Reset() {
	*x = GetInfoResourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_response_get_info_resource_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInfoResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResourceResponse) ProtoMessage() {}

func (x *GetInfoResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_response_get_info_resource_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResourceResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResourceResponse) Descriptor() ([]byte, []int) {
	return file_message_response_get_info_resource_response_proto_rawDescGZIP(), []int{0}
}

func (m *GetInfoResourceResponse) GetData() isGetInfoResourceResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *GetInfoResourceResponse) GetSuccess() *GetInfoResourceResponse_Success {
	if x, ok := x.GetData().(*GetInfoResourceResponse_Success_); ok {
		return x.Success
	}
	return nil
}

func (x *GetInfoResourceResponse) GetError() *common.ErrorMessage {
	if x, ok := x.GetData().(*GetInfoResourceResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isGetInfoResourceResponse_Data interface {
	isGetInfoResourceResponse_Data()
}

type GetInfoResourceResponse_Success_ struct {
	Success *GetInfoResourceResponse_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type GetInfoResourceResponse_Error struct {
	Error *common.ErrorMessage `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetInfoResourceResponse_Success_) isGetInfoResourceResponse_Data() {}

func (*GetInfoResourceResponse_Error) isGetInfoResourceResponse_Data() {}

type GetInfoResourceResponse_SuccessElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource common.InfoResource `protobuf:"varint,1,opt,name=resource,proto3,enum=common.InfoResource" json:"resource,omitempty"`
	Data     []byte              `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetInfoResourceResponse_SuccessElement) Reset() {
	*x = GetInfoResourceResponse_SuccessElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_response_get_info_resource_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInfoResourceResponse_SuccessElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResourceResponse_SuccessElement) ProtoMessage() {}

func (x *GetInfoResourceResponse_SuccessElement) ProtoReflect() protoreflect.Message {
	mi := &file_message_response_get_info_resource_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResourceResponse_SuccessElement.ProtoReflect.Descriptor instead.
func (*GetInfoResourceResponse_SuccessElement) Descriptor() ([]byte, []int) {
	return file_message_response_get_info_resource_response_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetInfoResourceResponse_SuccessElement) GetResource() common.InfoResource {
	if x != nil {
		return x.Resource
	}
	return common.InfoResource(0)
}

func (x *GetInfoResourceResponse_SuccessElement) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetInfoResourceResponse_Success struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datas []*GetInfoResourceResponse_SuccessElement `protobuf:"bytes,1,rep,name=datas,proto3" json:"datas,omitempty"`
}

func (x *GetInfoResourceResponse_Success) Reset() {
	*x = GetInfoResourceResponse_Success{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_response_get_info_resource_response_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInfoResourceResponse_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResourceResponse_Success) ProtoMessage() {}

func (x *GetInfoResourceResponse_Success) ProtoReflect() protoreflect.Message {
	mi := &file_message_response_get_info_resource_response_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResourceResponse_Success.ProtoReflect.Descriptor instead.
func (*GetInfoResourceResponse_Success) Descriptor() ([]byte, []int) {
	return file_message_response_get_info_resource_response_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetInfoResourceResponse_Success) GetDatas() []*GetInfoResourceResponse_SuccessElement {
	if x != nil {
		return x.Datas
	}
	return nil
}

var File_message_response_get_info_resource_response_proto protoreflect.FileDescriptor

var file_message_response_get_info_resource_response_proto_rawDesc = []byte{
	0x0a, 0x31, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x22, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x22, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc1, 0x02, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x45, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x29, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x48, 0x00, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x2c, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x56, 0x0a, 0x0e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x51,
	0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x46, 0x0a, 0x05, 0x64, 0x61, 0x74,
	0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61,
	0x73, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x16, 0x5a, 0x14, 0x70, 0x6b, 0x67,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_response_get_info_resource_response_proto_rawDescOnce sync.Once
	file_message_response_get_info_resource_response_proto_rawDescData = file_message_response_get_info_resource_response_proto_rawDesc
)

func file_message_response_get_info_resource_response_proto_rawDescGZIP() []byte {
	file_message_response_get_info_resource_response_proto_rawDescOnce.Do(func() {
		file_message_response_get_info_resource_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_response_get_info_resource_response_proto_rawDescData)
	})
	return file_message_response_get_info_resource_response_proto_rawDescData
}

var file_message_response_get_info_resource_response_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_message_response_get_info_resource_response_proto_goTypes = []interface{}{
	(*GetInfoResourceResponse)(nil),                // 0: response.GetInfoResourceResponse
	(*GetInfoResourceResponse_SuccessElement)(nil), // 1: response.GetInfoResourceResponse.SuccessElement
	(*GetInfoResourceResponse_Success)(nil),        // 2: response.GetInfoResourceResponse.Success
	(*common.ErrorMessage)(nil),                    // 3: common.ErrorMessage
	(common.InfoResource)(0),                       // 4: common.InfoResource
}
var file_message_response_get_info_resource_response_proto_depIdxs = []int32{
	2, // 0: response.GetInfoResourceResponse.success:type_name -> response.GetInfoResourceResponse.Success
	3, // 1: response.GetInfoResourceResponse.error:type_name -> common.ErrorMessage
	4, // 2: response.GetInfoResourceResponse.SuccessElement.resource:type_name -> common.InfoResource
	1, // 3: response.GetInfoResourceResponse.Success.datas:type_name -> response.GetInfoResourceResponse.SuccessElement
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_message_response_get_info_resource_response_proto_init() }
func file_message_response_get_info_resource_response_proto_init() {
	if File_message_response_get_info_resource_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_response_get_info_resource_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInfoResourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_response_get_info_resource_response_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInfoResourceResponse_SuccessElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_response_get_info_resource_response_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInfoResourceResponse_Success); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_response_get_info_resource_response_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*GetInfoResourceResponse_Success_)(nil),
		(*GetInfoResourceResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_response_get_info_resource_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_response_get_info_resource_response_proto_goTypes,
		DependencyIndexes: file_message_response_get_info_resource_response_proto_depIdxs,
		MessageInfos:      file_message_response_get_info_resource_response_proto_msgTypes,
	}.Build()
	File_message_response_get_info_resource_response_proto = out.File
	file_message_response_get_info_resource_response_proto_rawDesc = nil
	file_message_response_get_info_resource_response_proto_goTypes = nil
	file_message_response_get_info_resource_response_proto_depIdxs = nil
}
