// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: message/response/get_module_log_response.proto

package response

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "pkg/message/common"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetModuleLogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*GetModuleLogResponse_Success_
	//	*GetModuleLogResponse_Error
	Data isGetModuleLogResponse_Data `protobuf_oneof:"data"`
}

func (x *GetModuleLogResponse) Reset() {
	*x = GetModuleLogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_response_get_module_log_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetModuleLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleLogResponse) ProtoMessage() {}

func (x *GetModuleLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_response_get_module_log_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleLogResponse.ProtoReflect.Descriptor instead.
func (*GetModuleLogResponse) Descriptor() ([]byte, []int) {
	return file_message_response_get_module_log_response_proto_rawDescGZIP(), []int{0}
}

func (m *GetModuleLogResponse) GetData() isGetModuleLogResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *GetModuleLogResponse) GetSuccess() *GetModuleLogResponse_Success {
	if x, ok := x.GetData().(*GetModuleLogResponse_Success_); ok {
		return x.Success
	}
	return nil
}

func (x *GetModuleLogResponse) GetError() *common.ErrorMessage {
	if x, ok := x.GetData().(*GetModuleLogResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isGetModuleLogResponse_Data interface {
	isGetModuleLogResponse_Data()
}

type GetModuleLogResponse_Success_ struct {
	Success *GetModuleLogResponse_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type GetModuleLogResponse_Error struct {
	Error *common.ErrorMessage `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetModuleLogResponse_Success_) isGetModuleLogResponse_Data() {}

func (*GetModuleLogResponse_Error) isGetModuleLogResponse_Data() {}

type GetModuleLogResponse_Success struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessName string   `protobuf:"bytes,1,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	Log         []string `protobuf:"bytes,2,rep,name=log,proto3" json:"log,omitempty"`
}

func (x *GetModuleLogResponse_Success) Reset() {
	*x = GetModuleLogResponse_Success{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_response_get_module_log_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetModuleLogResponse_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleLogResponse_Success) ProtoMessage() {}

func (x *GetModuleLogResponse_Success) ProtoReflect() protoreflect.Message {
	mi := &file_message_response_get_module_log_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleLogResponse_Success.ProtoReflect.Descriptor instead.
func (*GetModuleLogResponse_Success) Descriptor() ([]byte, []int) {
	return file_message_response_get_module_log_response_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetModuleLogResponse_Success) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *GetModuleLogResponse_Success) GetLog() []string {
	if x != nil {
		return x.Log
	}
	return nil
}

var File_message_response_get_module_log_response_proto protoreflect.FileDescriptor

var file_message_response_get_module_log_response_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x6c, 0x6f,
	0x67, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x22, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd0,
	0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4c, 0x6f, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4c, 0x6f, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x2c, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x3e, 0x0a, 0x07, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x42, 0x16, 0x5a, 0x14, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_message_response_get_module_log_response_proto_rawDescOnce sync.Once
	file_message_response_get_module_log_response_proto_rawDescData = file_message_response_get_module_log_response_proto_rawDesc
)

func file_message_response_get_module_log_response_proto_rawDescGZIP() []byte {
	file_message_response_get_module_log_response_proto_rawDescOnce.Do(func() {
		file_message_response_get_module_log_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_response_get_module_log_response_proto_rawDescData)
	})
	return file_message_response_get_module_log_response_proto_rawDescData
}

var file_message_response_get_module_log_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_message_response_get_module_log_response_proto_goTypes = []interface{}{
	(*GetModuleLogResponse)(nil),         // 0: response.GetModuleLogResponse
	(*GetModuleLogResponse_Success)(nil), // 1: response.GetModuleLogResponse.Success
	(*common.ErrorMessage)(nil),          // 2: common.ErrorMessage
}
var file_message_response_get_module_log_response_proto_depIdxs = []int32{
	1, // 0: response.GetModuleLogResponse.success:type_name -> response.GetModuleLogResponse.Success
	2, // 1: response.GetModuleLogResponse.error:type_name -> common.ErrorMessage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_response_get_module_log_response_proto_init() }
func file_message_response_get_module_log_response_proto_init() {
	if File_message_response_get_module_log_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_response_get_module_log_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetModuleLogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_response_get_module_log_response_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetModuleLogResponse_Success); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_response_get_module_log_response_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*GetModuleLogResponse_Success_)(nil),
		(*GetModuleLogResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_response_get_module_log_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_response_get_module_log_response_proto_goTypes,
		DependencyIndexes: file_message_response_get_module_log_response_proto_depIdxs,
		MessageInfos:      file_message_response_get_module_log_response_proto_msgTypes,
	}.Build()
	File_message_response_get_module_log_response_proto = out.File
	file_message_response_get_module_log_response_proto_rawDesc = nil
	file_message_response_get_module_log_response_proto_goTypes = nil
	file_message_response_get_module_log_response_proto_depIdxs = nil
}
