// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: message/response/set_module_reboot_cond_response.proto

package response

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "pkg/message/common"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetModuleRebootCondResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*SetModuleRebootCondResponse_Success
	//	*SetModuleRebootCondResponse_Error
	Data isSetModuleRebootCondResponse_Data `protobuf_oneof:"data"`
}

func (x *SetModuleRebootCondResponse) Reset() {
	*x = SetModuleRebootCondResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_response_set_module_reboot_cond_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetModuleRebootCondResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModuleRebootCondResponse) ProtoMessage() {}

func (x *SetModuleRebootCondResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_response_set_module_reboot_cond_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModuleRebootCondResponse.ProtoReflect.Descriptor instead.
func (*SetModuleRebootCondResponse) Descriptor() ([]byte, []int) {
	return file_message_response_set_module_reboot_cond_response_proto_rawDescGZIP(), []int{0}
}

func (m *SetModuleRebootCondResponse) GetData() isSetModuleRebootCondResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *SetModuleRebootCondResponse) GetSuccess() bool {
	if x, ok := x.GetData().(*SetModuleRebootCondResponse_Success); ok {
		return x.Success
	}
	return false
}

func (x *SetModuleRebootCondResponse) GetError() *common.ErrorMessage {
	if x, ok := x.GetData().(*SetModuleRebootCondResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isSetModuleRebootCondResponse_Data interface {
	isSetModuleRebootCondResponse_Data()
}

type SetModuleRebootCondResponse_Success struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3,oneof"`
}

type SetModuleRebootCondResponse_Error struct {
	Error *common.ErrorMessage `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*SetModuleRebootCondResponse_Success) isSetModuleRebootCondResponse_Data() {}

func (*SetModuleRebootCondResponse_Error) isSetModuleRebootCondResponse_Data() {}

var File_message_response_set_module_reboot_cond_response_proto protoreflect.FileDescriptor

var file_message_response_set_module_reboot_cond_response_proto_rawDesc = []byte{
	0x0a, 0x36, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2f, 0x73, 0x65, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x72, 0x65,
	0x62, 0x6f, 0x6f, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x1a, 0x22, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6f, 0x0a, 0x1b, 0x53, 0x65, 0x74, 0x4d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x52, 0x65, 0x62, 0x6f, 0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x2c, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42,
	0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x16, 0x5a, 0x14, 0x70, 0x6b, 0x67, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_response_set_module_reboot_cond_response_proto_rawDescOnce sync.Once
	file_message_response_set_module_reboot_cond_response_proto_rawDescData = file_message_response_set_module_reboot_cond_response_proto_rawDesc
)

func file_message_response_set_module_reboot_cond_response_proto_rawDescGZIP() []byte {
	file_message_response_set_module_reboot_cond_response_proto_rawDescOnce.Do(func() {
		file_message_response_set_module_reboot_cond_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_response_set_module_reboot_cond_response_proto_rawDescData)
	})
	return file_message_response_set_module_reboot_cond_response_proto_rawDescData
}

var file_message_response_set_module_reboot_cond_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_response_set_module_reboot_cond_response_proto_goTypes = []interface{}{
	(*SetModuleRebootCondResponse)(nil), // 0: response.SetModuleRebootCondResponse
	(*common.ErrorMessage)(nil),         // 1: common.ErrorMessage
}
var file_message_response_set_module_reboot_cond_response_proto_depIdxs = []int32{
	1, // 0: response.SetModuleRebootCondResponse.error:type_name -> common.ErrorMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_response_set_module_reboot_cond_response_proto_init() }
func file_message_response_set_module_reboot_cond_response_proto_init() {
	if File_message_response_set_module_reboot_cond_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_response_set_module_reboot_cond_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetModuleRebootCondResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_response_set_module_reboot_cond_response_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SetModuleRebootCondResponse_Success)(nil),
		(*SetModuleRebootCondResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_response_set_module_reboot_cond_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_response_set_module_reboot_cond_response_proto_goTypes,
		DependencyIndexes: file_message_response_set_module_reboot_cond_response_proto_depIdxs,
		MessageInfos:      file_message_response_set_module_reboot_cond_response_proto_msgTypes,
	}.Build()
	File_message_response_set_module_reboot_cond_response_proto = out.File
	file_message_response_set_module_reboot_cond_response_proto_rawDesc = nil
	file_message_response_set_module_reboot_cond_response_proto_goTypes = nil
	file_message_response_set_module_reboot_cond_response_proto_depIdxs = nil
}
