// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: message/response/switch_server_onoff_response.proto

package response

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "pkg/message/common"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SwitchServerOnOffResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*SwitchServerOnOffResponse_Success_
	//	*SwitchServerOnOffResponse_Error
	Data isSwitchServerOnOffResponse_Data `protobuf_oneof:"data"`
}

func (x *SwitchServerOnOffResponse) Reset() {
	*x = SwitchServerOnOffResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_response_switch_server_onoff_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwitchServerOnOffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchServerOnOffResponse) ProtoMessage() {}

func (x *SwitchServerOnOffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_response_switch_server_onoff_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchServerOnOffResponse.ProtoReflect.Descriptor instead.
func (*SwitchServerOnOffResponse) Descriptor() ([]byte, []int) {
	return file_message_response_switch_server_onoff_response_proto_rawDescGZIP(), []int{0}
}

func (m *SwitchServerOnOffResponse) GetData() isSwitchServerOnOffResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *SwitchServerOnOffResponse) GetSuccess() *SwitchServerOnOffResponse_Success {
	if x, ok := x.GetData().(*SwitchServerOnOffResponse_Success_); ok {
		return x.Success
	}
	return nil
}

func (x *SwitchServerOnOffResponse) GetError() *common.ErrorMessage {
	if x, ok := x.GetData().(*SwitchServerOnOffResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isSwitchServerOnOffResponse_Data interface {
	isSwitchServerOnOffResponse_Data()
}

type SwitchServerOnOffResponse_Success_ struct {
	Success *SwitchServerOnOffResponse_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type SwitchServerOnOffResponse_Error struct {
	Error *common.ErrorMessage `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*SwitchServerOnOffResponse_Success_) isSwitchServerOnOffResponse_Data() {}

func (*SwitchServerOnOffResponse_Error) isSwitchServerOnOffResponse_Data() {}

type SwitchServerOnOffResponse_Success struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource common.InfoResource `protobuf:"varint,1,opt,name=resource,proto3,enum=common.InfoResource" json:"resource,omitempty"`
	Status   bool                `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SwitchServerOnOffResponse_Success) Reset() {
	*x = SwitchServerOnOffResponse_Success{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_response_switch_server_onoff_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwitchServerOnOffResponse_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchServerOnOffResponse_Success) ProtoMessage() {}

func (x *SwitchServerOnOffResponse_Success) ProtoReflect() protoreflect.Message {
	mi := &file_message_response_switch_server_onoff_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchServerOnOffResponse_Success.ProtoReflect.Descriptor instead.
func (*SwitchServerOnOffResponse_Success) Descriptor() ([]byte, []int) {
	return file_message_response_switch_server_onoff_response_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SwitchServerOnOffResponse_Success) GetResource() common.InfoResource {
	if x != nil {
		return x.Resource
	}
	return common.InfoResource(0)
}

func (x *SwitchServerOnOffResponse_Success) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_message_response_switch_server_onoff_response_proto protoreflect.FileDescriptor

var file_message_response_switch_server_onoff_response_proto_rawDesc = []byte{
	0x0a, 0x33, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x6f, 0x6e, 0x6f, 0x66, 0x66, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a,
	0x22, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xef, 0x01, 0x0a, 0x19, 0x53, 0x77, 0x69, 0x74,
	0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4f, 0x6e, 0x4f, 0x66, 0x66, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4f, 0x6e,
	0x4f, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x2c,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x53, 0x0a, 0x07,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x30, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52,
	0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x16, 0x5a, 0x14, 0x70, 0x6b, 0x67,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_response_switch_server_onoff_response_proto_rawDescOnce sync.Once
	file_message_response_switch_server_onoff_response_proto_rawDescData = file_message_response_switch_server_onoff_response_proto_rawDesc
)

func file_message_response_switch_server_onoff_response_proto_rawDescGZIP() []byte {
	file_message_response_switch_server_onoff_response_proto_rawDescOnce.Do(func() {
		file_message_response_switch_server_onoff_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_response_switch_server_onoff_response_proto_rawDescData)
	})
	return file_message_response_switch_server_onoff_response_proto_rawDescData
}

var file_message_response_switch_server_onoff_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_message_response_switch_server_onoff_response_proto_goTypes = []interface{}{
	(*SwitchServerOnOffResponse)(nil),         // 0: response.SwitchServerOnOffResponse
	(*SwitchServerOnOffResponse_Success)(nil), // 1: response.SwitchServerOnOffResponse.Success
	(*common.ErrorMessage)(nil),               // 2: common.ErrorMessage
	(common.InfoResource)(0),                  // 3: common.InfoResource
}
var file_message_response_switch_server_onoff_response_proto_depIdxs = []int32{
	1, // 0: response.SwitchServerOnOffResponse.success:type_name -> response.SwitchServerOnOffResponse.Success
	2, // 1: response.SwitchServerOnOffResponse.error:type_name -> common.ErrorMessage
	3, // 2: response.SwitchServerOnOffResponse.Success.resource:type_name -> common.InfoResource
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_message_response_switch_server_onoff_response_proto_init() }
func file_message_response_switch_server_onoff_response_proto_init() {
	if File_message_response_switch_server_onoff_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_response_switch_server_onoff_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwitchServerOnOffResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_response_switch_server_onoff_response_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwitchServerOnOffResponse_Success); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_response_switch_server_onoff_response_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SwitchServerOnOffResponse_Success_)(nil),
		(*SwitchServerOnOffResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_response_switch_server_onoff_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_response_switch_server_onoff_response_proto_goTypes,
		DependencyIndexes: file_message_response_switch_server_onoff_response_proto_depIdxs,
		MessageInfos:      file_message_response_switch_server_onoff_response_proto_msgTypes,
	}.Build()
	File_message_response_switch_server_onoff_response_proto = out.File
	file_message_response_switch_server_onoff_response_proto_rawDesc = nil
	file_message_response_switch_server_onoff_response_proto_goTypes = nil
	file_message_response_switch_server_onoff_response_proto_depIdxs = nil
}
