// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: message/common/access_modiffier.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessModiffier int32

const (
	AccessModiffier_PRIVATE AccessModiffier = 0
	AccessModiffier_PUBLIC  AccessModiffier = 1
)

// Enum value maps for AccessModiffier.
var (
	AccessModiffier_name = map[int32]string{
		0: "PRIVATE",
		1: "PUBLIC",
	}
	AccessModiffier_value = map[string]int32{
		"PRIVATE": 0,
		"PUBLIC":  1,
	}
)

func (x AccessModiffier) Enum() *AccessModiffier {
	p := new(AccessModiffier)
	*p = x
	return p
}

func (x AccessModiffier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessModiffier) Descriptor() protoreflect.EnumDescriptor {
	return file_message_common_access_modiffier_proto_enumTypes[0].Descriptor()
}

func (AccessModiffier) Type() protoreflect.EnumType {
	return &file_message_common_access_modiffier_proto_enumTypes[0]
}

func (x AccessModiffier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessModiffier.Descriptor instead.
func (AccessModiffier) EnumDescriptor() ([]byte, []int) {
	return file_message_common_access_modiffier_proto_rawDescGZIP(), []int{0}
}

var File_message_common_access_modiffier_proto protoreflect.FileDescriptor

var file_message_common_access_modiffier_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x66, 0x69, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a,
	0x2a, 0x0a, 0x0f, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x66, 0x69,
	0x65, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x49, 0x56, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12,
	0x0a, 0x0a, 0x06, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x10, 0x01, 0x42, 0x14, 0x5a, 0x12, 0x70,
	0x6b, 0x67, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_common_access_modiffier_proto_rawDescOnce sync.Once
	file_message_common_access_modiffier_proto_rawDescData = file_message_common_access_modiffier_proto_rawDesc
)

func file_message_common_access_modiffier_proto_rawDescGZIP() []byte {
	file_message_common_access_modiffier_proto_rawDescOnce.Do(func() {
		file_message_common_access_modiffier_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_common_access_modiffier_proto_rawDescData)
	})
	return file_message_common_access_modiffier_proto_rawDescData
}

var file_message_common_access_modiffier_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_common_access_modiffier_proto_goTypes = []interface{}{
	(AccessModiffier)(0), // 0: common.AccessModiffier
}
var file_message_common_access_modiffier_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_common_access_modiffier_proto_init() }
func file_message_common_access_modiffier_proto_init() {
	if File_message_common_access_modiffier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_common_access_modiffier_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_common_access_modiffier_proto_goTypes,
		DependencyIndexes: file_message_common_access_modiffier_proto_depIdxs,
		EnumInfos:         file_message_common_access_modiffier_proto_enumTypes,
	}.Build()
	File_message_common_access_modiffier_proto = out.File
	file_message_common_access_modiffier_proto_rawDesc = nil
	file_message_common_access_modiffier_proto_goTypes = nil
	file_message_common_access_modiffier_proto_depIdxs = nil
}
