// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: message/common/cond.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Compare int32

const (
	Compare_EQUAL_TO     Compare = 0
	Compare_LESS_THAN    Compare = 1
	Compare_GREATER_THAN Compare = 2
)

// Enum value maps for Compare.
var (
	Compare_name = map[int32]string{
		0: "EQUAL_TO",
		1: "LESS_THAN",
		2: "GREATER_THAN",
	}
	Compare_value = map[string]int32{
		"EQUAL_TO":     0,
		"LESS_THAN":    1,
		"GREATER_THAN": 2,
	}
)

func (x Compare) Enum() *Compare {
	p := new(Compare)
	*p = x
	return p
}

func (x Compare) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compare) Descriptor() protoreflect.EnumDescriptor {
	return file_message_common_cond_proto_enumTypes[0].Descriptor()
}

func (Compare) Type() protoreflect.EnumType {
	return &file_message_common_cond_proto_enumTypes[0]
}

func (x Compare) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compare.Descriptor instead.
func (Compare) EnumDescriptor() ([]byte, []int) {
	return file_message_common_cond_proto_rawDescGZIP(), []int{0}
}

type ResourceCond struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value   int32   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Compare Compare `protobuf:"varint,2,opt,name=compare,proto3,enum=common.Compare" json:"compare,omitempty"`
	// Types that are assignable to Resource:
	//
	//	*ResourceCond_Hardware
	//	*ResourceCond_Info
	Resource isResourceCond_Resource `protobuf_oneof:"resource"`
}

func (x *ResourceCond) Reset() {
	*x = ResourceCond{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_common_cond_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceCond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceCond) ProtoMessage() {}

func (x *ResourceCond) ProtoReflect() protoreflect.Message {
	mi := &file_message_common_cond_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceCond.ProtoReflect.Descriptor instead.
func (*ResourceCond) Descriptor() ([]byte, []int) {
	return file_message_common_cond_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceCond) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ResourceCond) GetCompare() Compare {
	if x != nil {
		return x.Compare
	}
	return Compare_EQUAL_TO
}

func (m *ResourceCond) GetResource() isResourceCond_Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (x *ResourceCond) GetHardware() HardwareResource {
	if x, ok := x.GetResource().(*ResourceCond_Hardware); ok {
		return x.Hardware
	}
	return HardwareResource_CPU
}

func (x *ResourceCond) GetInfo() InfoResource {
	if x, ok := x.GetResource().(*ResourceCond_Info); ok {
		return x.Info
	}
	return InfoResource_IP
}

type isResourceCond_Resource interface {
	isResourceCond_Resource()
}

type ResourceCond_Hardware struct {
	Hardware HardwareResource `protobuf:"varint,3,opt,name=hardware,proto3,enum=common.HardwareResource,oneof"`
}

type ResourceCond_Info struct {
	Info InfoResource `protobuf:"varint,4,opt,name=info,proto3,enum=common.InfoResource,oneof"`
}

func (*ResourceCond_Hardware) isResourceCond_Resource() {}

func (*ResourceCond_Info) isResourceCond_Resource() {}

var File_message_common_cond_proto protoreflect.FileDescriptor

var file_message_common_cond_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x63, 0x6f, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x1a, 0x26, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2f, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x69, 0x6e, 0x66, 0x6f,
	0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xbf, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x29, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72,
	0x65, 0x12, 0x36, 0x0a, 0x08, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x48, 0x61, 0x72,
	0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x00, 0x52,
	0x08, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x00, 0x52,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2a, 0x38, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x12, 0x0c, 0x0a, 0x08,
	0x45, 0x51, 0x55, 0x41, 0x4c, 0x5f, 0x54, 0x4f, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x45,
	0x53, 0x53, 0x5f, 0x54, 0x48, 0x41, 0x4e, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x47, 0x52, 0x45,
	0x41, 0x54, 0x45, 0x52, 0x5f, 0x54, 0x48, 0x41, 0x4e, 0x10, 0x02, 0x42, 0x14, 0x5a, 0x12, 0x70,
	0x6b, 0x67, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_common_cond_proto_rawDescOnce sync.Once
	file_message_common_cond_proto_rawDescData = file_message_common_cond_proto_rawDesc
)

func file_message_common_cond_proto_rawDescGZIP() []byte {
	file_message_common_cond_proto_rawDescOnce.Do(func() {
		file_message_common_cond_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_common_cond_proto_rawDescData)
	})
	return file_message_common_cond_proto_rawDescData
}

var file_message_common_cond_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_common_cond_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_common_cond_proto_goTypes = []interface{}{
	(Compare)(0),          // 0: common.Compare
	(*ResourceCond)(nil),  // 1: common.ResourceCond
	(HardwareResource)(0), // 2: common.HardwareResource
	(InfoResource)(0),     // 3: common.InfoResource
}
var file_message_common_cond_proto_depIdxs = []int32{
	0, // 0: common.ResourceCond.compare:type_name -> common.Compare
	2, // 1: common.ResourceCond.hardware:type_name -> common.HardwareResource
	3, // 2: common.ResourceCond.info:type_name -> common.InfoResource
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_message_common_cond_proto_init() }
func file_message_common_cond_proto_init() {
	if File_message_common_cond_proto != nil {
		return
	}
	file_message_common_hardware_resource_proto_init()
	file_message_common_info_resource_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_message_common_cond_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceCond); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_common_cond_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ResourceCond_Hardware)(nil),
		(*ResourceCond_Info)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_common_cond_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_common_cond_proto_goTypes,
		DependencyIndexes: file_message_common_cond_proto_depIdxs,
		EnumInfos:         file_message_common_cond_proto_enumTypes,
		MessageInfos:      file_message_common_cond_proto_msgTypes,
	}.Build()
	File_message_common_cond_proto = out.File
	file_message_common_cond_proto_rawDesc = nil
	file_message_common_cond_proto_goTypes = nil
	file_message_common_cond_proto_depIdxs = nil
}
