// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: message/common/hardware_resource.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HardwareResource int32

const (
	HardwareResource_CPU     HardwareResource = 0
	HardwareResource_MEMORY  HardwareResource = 1
	HardwareResource_DISK    HardwareResource = 2
	HardwareResource_NETWORK HardwareResource = 3
)

// Enum value maps for HardwareResource.
var (
	HardwareResource_name = map[int32]string{
		0: "CPU",
		1: "MEMORY",
		2: "DISK",
		3: "NETWORK",
	}
	HardwareResource_value = map[string]int32{
		"CPU":     0,
		"MEMORY":  1,
		"DISK":    2,
		"NETWORK": 3,
	}
)

func (x HardwareResource) Enum() *HardwareResource {
	p := new(HardwareResource)
	*p = x
	return p
}

func (x HardwareResource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HardwareResource) Descriptor() protoreflect.EnumDescriptor {
	return file_message_common_hardware_resource_proto_enumTypes[0].Descriptor()
}

func (HardwareResource) Type() protoreflect.EnumType {
	return &file_message_common_hardware_resource_proto_enumTypes[0]
}

func (x HardwareResource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HardwareResource.Descriptor instead.
func (HardwareResource) EnumDescriptor() ([]byte, []int) {
	return file_message_common_hardware_resource_proto_rawDescGZIP(), []int{0}
}

var File_message_common_hardware_resource_proto protoreflect.FileDescriptor

var file_message_common_hardware_resource_proto_rawDesc = []byte{
	0x0a, 0x26, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2a, 0x3e, 0x0a, 0x10, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x50, 0x55, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x4d, 0x45, 0x4d, 0x4f, 0x52, 0x59, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x49, 0x53,
	0x4b, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x10, 0x03,
	0x42, 0x14, 0x5a, 0x12, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_common_hardware_resource_proto_rawDescOnce sync.Once
	file_message_common_hardware_resource_proto_rawDescData = file_message_common_hardware_resource_proto_rawDesc
)

func file_message_common_hardware_resource_proto_rawDescGZIP() []byte {
	file_message_common_hardware_resource_proto_rawDescOnce.Do(func() {
		file_message_common_hardware_resource_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_common_hardware_resource_proto_rawDescData)
	})
	return file_message_common_hardware_resource_proto_rawDescData
}

var file_message_common_hardware_resource_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_common_hardware_resource_proto_goTypes = []interface{}{
	(HardwareResource)(0), // 0: common.HardwareResource
}
var file_message_common_hardware_resource_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_common_hardware_resource_proto_init() }
func file_message_common_hardware_resource_proto_init() {
	if File_message_common_hardware_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_common_hardware_resource_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_common_hardware_resource_proto_goTypes,
		DependencyIndexes: file_message_common_hardware_resource_proto_depIdxs,
		EnumInfos:         file_message_common_hardware_resource_proto_enumTypes,
	}.Build()
	File_message_common_hardware_resource_proto = out.File
	file_message_common_hardware_resource_proto_rawDesc = nil
	file_message_common_hardware_resource_proto_goTypes = nil
	file_message_common_hardware_resource_proto_depIdxs = nil
}
