// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: message/common/info_resource.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoResource int32

const (
	InfoResource_IP           InfoResource = 0
	InfoResource_HOSTNAME     InfoResource = 1
	InfoResource_MODULE_INFO  InfoResource = 2
	InfoResource_MODULE_CNT   InfoResource = 3
	InfoResource_SERVER_POWER InfoResource = 4
)

// Enum value maps for InfoResource.
var (
	InfoResource_name = map[int32]string{
		0: "IP",
		1: "HOSTNAME",
		2: "MODULE_INFO",
		3: "MODULE_CNT",
		4: "SERVER_POWER",
	}
	InfoResource_value = map[string]int32{
		"IP":           0,
		"HOSTNAME":     1,
		"MODULE_INFO":  2,
		"MODULE_CNT":   3,
		"SERVER_POWER": 4,
	}
)

func (x InfoResource) Enum() *InfoResource {
	p := new(InfoResource)
	*p = x
	return p
}

func (x InfoResource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InfoResource) Descriptor() protoreflect.EnumDescriptor {
	return file_message_common_info_resource_proto_enumTypes[0].Descriptor()
}

func (InfoResource) Type() protoreflect.EnumType {
	return &file_message_common_info_resource_proto_enumTypes[0]
}

func (x InfoResource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InfoResource.Descriptor instead.
func (InfoResource) EnumDescriptor() ([]byte, []int) {
	return file_message_common_info_resource_proto_rawDescGZIP(), []int{0}
}

var File_message_common_info_resource_proto protoreflect.FileDescriptor

var file_message_common_info_resource_proto_rawDesc = []byte{
	0x0a, 0x22, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0x57, 0x0a, 0x0c,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x06, 0x0a, 0x02,
	0x49, 0x50, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x48, 0x4f, 0x53, 0x54, 0x4e, 0x41, 0x4d, 0x45,
	0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x4f, 0x44, 0x55, 0x4c, 0x45, 0x5f, 0x49, 0x4e, 0x46,
	0x4f, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x4f, 0x44, 0x55, 0x4c, 0x45, 0x5f, 0x43, 0x4e,
	0x54, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x50, 0x4f,
	0x57, 0x45, 0x52, 0x10, 0x04, 0x42, 0x14, 0x5a, 0x12, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_message_common_info_resource_proto_rawDescOnce sync.Once
	file_message_common_info_resource_proto_rawDescData = file_message_common_info_resource_proto_rawDesc
)

func file_message_common_info_resource_proto_rawDescGZIP() []byte {
	file_message_common_info_resource_proto_rawDescOnce.Do(func() {
		file_message_common_info_resource_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_common_info_resource_proto_rawDescData)
	})
	return file_message_common_info_resource_proto_rawDescData
}

var file_message_common_info_resource_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_common_info_resource_proto_goTypes = []interface{}{
	(InfoResource)(0), // 0: common.InfoResource
}
var file_message_common_info_resource_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_common_info_resource_proto_init() }
func file_message_common_info_resource_proto_init() {
	if File_message_common_info_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_common_info_resource_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_common_info_resource_proto_goTypes,
		DependencyIndexes: file_message_common_info_resource_proto_depIdxs,
		EnumInfos:         file_message_common_info_resource_proto_enumTypes,
	}.Build()
	File_message_common_info_resource_proto = out.File
	file_message_common_info_resource_proto_rawDesc = nil
	file_message_common_info_resource_proto_goTypes = nil
	file_message_common_info_resource_proto_depIdxs = nil
}
